/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/npl/commerce/-/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getOpenAPI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getOfferList"];
        put?: never;
        post: operations["_createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getOfferByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/updatePrice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_updatePrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/updateQuantity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_updateQuantity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Offer/{id}/checkExpiration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Offer_checkExpiration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getOrderList"];
        put?: never;
        post: operations["_createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getOrderByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/confirmOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_confirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/confirmPayment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_confirmPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/receivePayment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_receivePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/shipOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_shipOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/confirmDelivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_confirmDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/cancelOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Order/{id}/getOrderSummary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Order_getOrderSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Product/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getProductList"];
        put?: never;
        post: operations["_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Product/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getProductByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Product/{id}/updateDescription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Product_updateDescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Product/{id}/updateStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Product_updateStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Product/{id}/discontinue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Product_discontinue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/Product/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Product_reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getPurchaseOrderList"];
        put?: never;
        post: operations["_createPurchaseOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["_getPurchaseOrderByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/submitQuote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_submitQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/placeOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/shipOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_shipOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/closeOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_closeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/cancelOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/getOrderSummary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_getOrderSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/npl/commerce/PurchaseOrder/{id}/requiresApproval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PurchaseOrder_requiresApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "claims": {
         *         "preferred_email": [
         *           "john.doe@example.com"
         *         ]
         *       }
         *     }
         */
        _Party: {
            claims: {
                [key: string]: string[];
            };
        };
        _Period: {
            days: number;
            weeks: number;
            months: number;
            years: number;
        };
        _Error: {
            errorType?: string;
            /** Format: uuid */
            id?: string;
            idType?: string;
            message?: string;
            error?: string | null;
            origin?: {
                value?: string;
                /** Format: int32 */
                code?: number;
                originType?: string;
                id?: string;
                message?: string;
            } | null;
            stackTrace?: string | null;
            clientStackTrace?: ({
                name?: string;
                /** Format: uuid */
                protocolId?: string | null;
                elementType?: string;
                location?: {
                    file?: string;
                    /** Format: int32 */
                    line?: number;
                    sourceRef?: {
                        path?: string;
                        commit?: string;
                    } | null;
                };
            } | null)[] | null;
        };
        /** Format: uuid */
        Offer_Reference: string;
        /** Format: uuid */
        Product_Reference: string;
        /** @enum {string} */
        ItemCondition: "NewCondition" | "UsedCondition" | "RefurbishedCondition" | "DamagedCondition";
        MonetaryAmount: {
            value: number;
            currency: string;
        };
        /** @enum {string} */
        OfferStatus: "Draft" | "Published" | "Accepted" | "Expired" | "Withdrawn" | "Rejected";
        /** @enum {string} */
        OrderStatus: "OrderProblem" | "OrderProcessing" | "OrderPaymentDue" | "OrderInTransit" | "OrderDelivered" | "OrderPickupAvailable" | "OrderCancelled";
        /** @enum {string} */
        PaymentMethod: "Cash" | "CreditCard" | "Invoice" | "PayPal" | "BankTransfer" | "Cryptocurrency";
        PriceSpecification: {
            price: number;
            priceCurrency: string;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            validFrom: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            validThrough: string | null;
        };
        /** @enum {string} */
        ProductStatus: "InStock" | "OutOfStock" | "Discontinued" | "PreOrder";
        QuantitativeValue: {
            value: number;
            unitCode: string;
            unitText: string;
        };
        Offer: {
            /** Format: uuid */
            "@id": string;
            "@parties": components["schemas"]["Offer_Parties"];
            "@actions": components["schemas"]["Offer_Actions"];
            "@state": components["schemas"]["Offer_States"];
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            updatedAt: string;
            status: components["schemas"]["OfferStatus"];
            itemOffered: components["schemas"]["Product_Reference"];
            priceSpecification: components["schemas"]["PriceSpecification"];
            availableQuantity: components["schemas"]["QuantitativeValue"];
            deliveryLeadTime: number;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            validFrom: string;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            validThrough: string;
        };
        Offer_Parties: {
            seller: components["schemas"]["_Party"];
            buyer: components["schemas"]["_Party"];
        };
        Offer_Actions: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/publish
             */
            publish?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/accept
             */
            accept?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/reject
             */
            reject?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/withdraw
             */
            withdraw?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/updatePrice
             */
            updatePrice?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/updateQuantity
             */
            updateQuantity?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/checkExpiration
             */
            checkExpiration?: string;
        };
        Offer_List: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/?page=1&pageSize=10
             */
            "@prev"?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Offer/?page=3&pageSize=10
             */
            "@next"?: string;
            items: components["schemas"]["Offer"][];
            page?: number;
            /** @description Total number of accessible protocol instances. Only included if the `includeCount` query parameter was set. */
            totalItems?: number | null;
            /** @description Total number of accessible pages. Only included if the `includeCount` query parameter was set. */
            totalPages?: number | null;
        };
        Offer_Create: {
            itemOffered: components["schemas"]["Product_Reference"];
            priceSpecification: components["schemas"]["PriceSpecification"];
            availableQuantity: components["schemas"]["QuantitativeValue"];
            deliveryLeadTime: number;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            validFrom: string;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            validThrough: string;
            "@parties": components["schemas"]["Offer_Parties"];
        };
        /** @enum {string} */
        Offer_States: "draft" | "published" | "accepted" | "expired" | "withdrawn" | "rejected";
        Offer_UpdatePrice_Command: {
            newPrice: number;
        };
        Offer_UpdateQuantity_Command: {
            newQuantity: number;
        };
        Order: {
            /** Format: uuid */
            "@id": string;
            "@parties": components["schemas"]["Order_Parties"];
            "@actions": components["schemas"]["Order_Actions"];
            "@state": components["schemas"]["Order_States"];
            orderedItem: components["schemas"]["Product_Reference"];
            orderStatus: components["schemas"]["OrderStatus"];
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            paymentDueDate: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            expectedDeliveryDate: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            actualDeliveryDate: string | null;
            trackingNumber: string | null;
            paymentReceived: boolean;
            orderNumber: string;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            orderDate: string;
            acceptedOffer: components["schemas"]["Offer_Reference"];
            orderQuantity: components["schemas"]["QuantitativeValue"];
            price: components["schemas"]["MonetaryAmount"];
            paymentMethod: components["schemas"]["PaymentMethod"];
        };
        Order_Parties: {
            buyer: components["schemas"]["_Party"];
            sellerRole: components["schemas"]["_Party"];
        };
        Order_Actions: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/confirmOrder
             */
            confirmOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/confirmPayment
             */
            confirmPayment?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/receivePayment
             */
            receivePayment?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/shipOrder
             */
            shipOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/confirmDelivery
             */
            confirmDelivery?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/cancelOrder
             */
            cancelOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/getOrderSummary
             */
            getOrderSummary?: string;
        };
        Order_List: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/?page=1&pageSize=10
             */
            "@prev"?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Order/?page=3&pageSize=10
             */
            "@next"?: string;
            items: components["schemas"]["Order"][];
            page?: number;
            /** @description Total number of accessible protocol instances. Only included if the `includeCount` query parameter was set. */
            totalItems?: number | null;
            /** @description Total number of accessible pages. Only included if the `includeCount` query parameter was set. */
            totalPages?: number | null;
        };
        Order_Create: {
            orderNumber: string;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            orderDate: string;
            acceptedOffer: components["schemas"]["Offer_Reference"];
            orderQuantity: components["schemas"]["QuantitativeValue"];
            price: components["schemas"]["MonetaryAmount"];
            paymentMethod: components["schemas"]["PaymentMethod"];
            "@parties": components["schemas"]["Order_Parties"];
        };
        /** @enum {string} */
        Order_States: "OrderProcessing" | "OrderPaymentDue" | "OrderInTransit" | "OrderDelivered" | "OrderCancelled";
        Order_ConfirmOrder_Command: {
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            expectedDelivery: string;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            paymentDue: string;
        };
        Order_ShipOrder_Command: {
            tracking: string;
        };
        Order_CancelOrder_Command: {
            reason: string;
        };
        Product: {
            /** Format: uuid */
            "@id": string;
            "@parties": components["schemas"]["Product_Parties"];
            "@actions": components["schemas"]["Product_Actions"];
            "@state": components["schemas"]["Product_States"];
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            updatedAt: string;
            status: components["schemas"]["ProductStatus"];
            name: string;
            description: string;
            sku: string;
            gtin: string | null;
            brand: string | null;
            category: string;
            itemCondition: components["schemas"]["ItemCondition"];
        };
        Product_Parties: {
            seller: components["schemas"]["_Party"];
        };
        Product_Actions: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Product/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/updateDescription
             */
            updateDescription?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Product/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/updateStatus
             */
            updateStatus?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Product/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/discontinue
             */
            discontinue?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Product/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/reactivate
             */
            reactivate?: string;
        };
        Product_List: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Product/?page=1&pageSize=10
             */
            "@prev"?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/Product/?page=3&pageSize=10
             */
            "@next"?: string;
            items: components["schemas"]["Product"][];
            page?: number;
            /** @description Total number of accessible protocol instances. Only included if the `includeCount` query parameter was set. */
            totalItems?: number | null;
            /** @description Total number of accessible pages. Only included if the `includeCount` query parameter was set. */
            totalPages?: number | null;
        };
        Product_Create: {
            name: string;
            description: string;
            sku: string;
            gtin: string | null;
            brand: string | null;
            category: string;
            itemCondition: components["schemas"]["ItemCondition"];
            "@parties": components["schemas"]["Product_Parties"];
        };
        /** @enum {string} */
        Product_States: "active" | "discontinued";
        Product_UpdateDescription_Command: {
            newDescription: string;
        };
        Product_UpdateStatus_Command: {
            newStatus: components["schemas"]["ProductStatus"];
        };
        PurchaseOrder: {
            /** Format: uuid */
            "@id": string;
            "@parties": components["schemas"]["PurchaseOrder_Parties"];
            "@actions": components["schemas"]["PurchaseOrder_Actions"];
            "@state": components["schemas"]["PurchaseOrder_States"];
            APPROVAL_THRESHOLD: number;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            quoteSubmittedAt: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            approvalRequestedAt: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            approvedAt: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            orderedAt: string | null;
            /**
             * Format: zoned-date-time
             * @example 2006-01-02T15:04:05.999+01:00[Europe/Zurich]
             */
            shippedAt: string | null;
            trackingNumber: string | null;
            orderNumber: string;
            acceptedOffer: components["schemas"]["Offer_Reference"];
            quantity: number;
            unitPrice: number;
            total: number;
        };
        PurchaseOrder_Parties: {
            buyer: components["schemas"]["_Party"];
            seller: components["schemas"]["_Party"];
            approver: components["schemas"]["_Party"];
        };
        PurchaseOrder_Actions: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/submitQuote
             */
            submitQuote?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/approve
             */
            approve?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/placeOrder
             */
            placeOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/shipOrder
             */
            shipOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/closeOrder
             */
            closeOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/cancelOrder
             */
            cancelOrder?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/getOrderSummary
             */
            getOrderSummary?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/requiresApproval
             */
            requiresApproval?: string;
        };
        PurchaseOrder_List: {
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/?page=1&pageSize=10
             */
            "@prev"?: string;
            /**
             * Format: uri
             * @example http://localhost:12000/npl/commerce/PurchaseOrder/?page=3&pageSize=10
             */
            "@next"?: string;
            items: components["schemas"]["PurchaseOrder"][];
            page?: number;
            /** @description Total number of accessible protocol instances. Only included if the `includeCount` query parameter was set. */
            totalItems?: number | null;
            /** @description Total number of accessible pages. Only included if the `includeCount` query parameter was set. */
            totalPages?: number | null;
        };
        PurchaseOrder_Create: {
            orderNumber: string;
            acceptedOffer: components["schemas"]["Offer_Reference"];
            quantity: number;
            unitPrice: number;
            total: number;
            "@parties": components["schemas"]["PurchaseOrder_Parties"];
        };
        /** @enum {string} */
        PurchaseOrder_States: "Requested" | "Quoted" | "ApprovalRequired" | "Approved" | "Ordered" | "Shipped" | "Closed" | "Cancelled";
        PurchaseOrder_ShipOrder_Command: {
            tracking: string;
        };
        PurchaseOrder_CancelOrder_Command: {
            reason: string;
        };
    };
    responses: {
        /** @description Bad Request */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["_Error"];
            };
        };
        /** @description Unauthorized */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["_Error"];
            };
        };
        /** @description Forbidden */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["_Error"];
            };
        };
        /** @description Not Found */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["_Error"];
            };
        };
        /** @description Internal Server Error */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["_Error"];
            };
        };
    };
    parameters: {
        /** @description Optional parameter to require a specific API version */
        API_Version: string;
        /** @description Optional parameter to require a specific NPL Tag */
        NPL_Tag: string;
        ProtocolID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _getOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    _getOfferList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Include `totalItems` and `totalPages` in the response if set. This option is very expensive, so should be avoided when possible. */
                includeCount?: boolean;
                /** @description Sort the protocol list by the given type. Possible values are [created, modified]. Requires `order` parameter to be set. */
                sort?: string;
                /** @description Return search results in the given order. Possible values are 'asc' and 'desc'. Requires `sort` parameter to be set. */
                order?: string;
                /** @description Filter protocols whose current state is one of the provided values. May be repeated: e.g. ?state=active&state=paused */
                state?: string[];
                /** @description Filter protocols modified after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedAfter?: string;
                /** @description Filter protocols modified before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedBefore?: string;
                /** @description Filter protocols created after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdAfter?: string;
                /** @description Filter protocols created before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdBefore?: string;
            };
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accessible protocol instances of this type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer_List"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _createOffer: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Offer_Create"];
            };
        };
        responses: {
            /** @description The new protocol instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _getOfferByID: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The protocol instance with this ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_publish: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_accept: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_reject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_withdraw: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_updatePrice: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Offer_UpdatePrice_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_updateQuantity: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Offer_UpdateQuantity_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Offer_checkExpiration: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    _getOrderList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Include `totalItems` and `totalPages` in the response if set. This option is very expensive, so should be avoided when possible. */
                includeCount?: boolean;
                /** @description Sort the protocol list by the given type. Possible values are [created, modified]. Requires `order` parameter to be set. */
                sort?: string;
                /** @description Return search results in the given order. Possible values are 'asc' and 'desc'. Requires `sort` parameter to be set. */
                order?: string;
                /** @description Filter protocols whose current state is one of the provided values. May be repeated: e.g. ?state=active&state=paused */
                state?: string[];
                /** @description Filter protocols modified after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedAfter?: string;
                /** @description Filter protocols modified before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedBefore?: string;
                /** @description Filter protocols created after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdAfter?: string;
                /** @description Filter protocols created before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdBefore?: string;
            };
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accessible protocol instances of this type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order_List"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _createOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order_Create"];
            };
        };
        responses: {
            /** @description The new protocol instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _getOrderByID: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The protocol instance with this ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_confirmOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order_ConfirmOrder_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_confirmPayment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_receivePayment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_shipOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order_ShipOrder_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_confirmDelivery: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_cancelOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order_CancelOrder_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Order_getOrderSummary: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    _getProductList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Include `totalItems` and `totalPages` in the response if set. This option is very expensive, so should be avoided when possible. */
                includeCount?: boolean;
                /** @description Sort the protocol list by the given type. Possible values are [created, modified]. Requires `order` parameter to be set. */
                sort?: string;
                /** @description Return search results in the given order. Possible values are 'asc' and 'desc'. Requires `sort` parameter to be set. */
                order?: string;
                /** @description Filter protocols whose current state is one of the provided values. May be repeated: e.g. ?state=active&state=paused */
                state?: string[];
                /** @description Filter protocols modified after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedAfter?: string;
                /** @description Filter protocols modified before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedBefore?: string;
                /** @description Filter protocols created after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdAfter?: string;
                /** @description Filter protocols created before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdBefore?: string;
            };
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accessible protocol instances of this type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product_List"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _createProduct: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product_Create"];
            };
        };
        responses: {
            /** @description The new protocol instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _getProductByID: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The protocol instance with this ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Product_updateDescription: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product_UpdateDescription_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Product_updateStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product_UpdateStatus_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Product_discontinue: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    Product_reactivate: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    _getPurchaseOrderList: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Include `totalItems` and `totalPages` in the response if set. This option is very expensive, so should be avoided when possible. */
                includeCount?: boolean;
                /** @description Sort the protocol list by the given type. Possible values are [created, modified]. Requires `order` parameter to be set. */
                sort?: string;
                /** @description Return search results in the given order. Possible values are 'asc' and 'desc'. Requires `sort` parameter to be set. */
                order?: string;
                /** @description Filter protocols whose current state is one of the provided values. May be repeated: e.g. ?state=active&state=paused */
                state?: string[];
                /** @description Filter protocols modified after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedAfter?: string;
                /** @description Filter protocols modified before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                modifiedBefore?: string;
                /** @description Filter protocols created after the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdAfter?: string;
                /** @description Filter protocols created before the given timestamp (inclusive). The timestamp must be in ISO-8601 format. */
                createdBefore?: string;
            };
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All accessible protocol instances of this type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrder_List"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _createPurchaseOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseOrder_Create"];
            };
        };
        responses: {
            /** @description The new protocol instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrder"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    _getPurchaseOrderByID: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The protocol instance with this ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseOrder"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_submitQuote: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_approve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_placeOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_shipOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseOrder_ShipOrder_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_closeOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_cancelOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseOrder_CancelOrder_Command"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_getOrderSummary: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    PurchaseOrder_requiresApproval: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional parameter to require a specific API version */
                "X-NPL-API"?: components["parameters"]["API_Version"];
                /** @description Optional parameter to require a specific NPL Tag */
                "X-NPL-TAG"?: components["parameters"]["NPL_Tag"];
            };
            path: {
                id: components["parameters"]["ProtocolID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
}
